### ISSUE TITLE
Documentation of all variables

### ISSUE THREAD

**Issue by DrPsychick** [DrPsychick/ansible-docker#7]
One example file with comments that explains all vairables
```
containers:
  containername:
    name: "mycontainer"
    ...
```
